<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Propuesta de San Valentín</title>
    <style>
        body {
            margin: 0;
            overflow: hidden;
        }

        #proposal-container {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            text-align: center;
            color: white;
        }

        #options-container {
            display: flex;
            justify-content: center;
            margin-top: 20px;
        }

        .option {
            margin: 0 10px;
            padding: 10px 20px;
            cursor: pointer;
            background-color: #ff4d4d; /* Rojo suave */
            border: 2px solid #ffffff;
            border-radius: 10px;
            font-size: 18px;
            color: #ffffff;
            transition: background-color 0.3s ease;
        }

        .option:hover {
            background-color: #e60000; /* Rojo más intenso al pasar el ratón */
        }

        #no-option {
            position: relative;
            animation: moveOption 2s infinite alternate;
        }

        @keyframes moveOption {
            0% {
                left: 0;
            }
            100% {
                left: 20px;
            }
        }
    </style>
</head>
<body>
    <img src="https://t3.ftcdn.net/jpg/05/66/67/76/360_F_566677664_v26wP2RbxSGTeaYy6yVzQe6anQKDEYI2.jpg" alt="Corazones de fondo" style="position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: -1;">
    <div id="proposal-container">
        <h1>¿Quieres ser mi San Valentín?</h1>
        
        <div id="options-container">
            <div class="option" onclick="mostrarMensaje('¡Qué bueno! ¡Estoy emocionadaaaaaa!')">Sí</div>
            <div id="no-option" class="option" onclick="mostrarMensaje('Oh, lo siento. ¡Intentemos otra vez!')">No</div>
        </div>
    </div>

    <script>
        function mostrarMensaje(mensaje) {
            alert(mensaje);
        }
    </script>
</body>
</html>


